name: tmdb_movie_app_riverpod
description: Flutter Movies app with Riverpod (TMDB API)
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  transparent_image: ^2.0.1
  dio: ^5.4.2+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  envied: ^0.5.4+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  go_router: ^13.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  envied_generator: ^0.5.4
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
